# Generated by Django 4.2.16 on 2026-05-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_seed_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Processing", "Processing"),
                    ("Processed", "Processed"),
                    ("ProcessingFailed", "Processing Failed"),
                    ("Archived", "Archived"),
                ],
                db_index=True,
                default="New",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sentiment",
            name="display_colour",
            field=models.CharField(
                help_text="Hex colour code, e.g. #28a745", max_length=7
            ),
        ),
    ]
