# Generated by Django 4.2.16 on 2026-04-18 01:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_feedback_status_alter_sentiment_display_colour'),
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodellog',
            name='correction_records_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodellog',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aimodellog',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aimodellog',
            name='training_samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aimodellog',
            name='validation_samples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='themecluster',
            name='cluster_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themecluster',
            name='dominant_sentiment',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='bias_test_results',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='model_type',
            field=models.CharField(choices=[('topic_classifier', 'Topic Classifier'), ('sentiment_analyser', 'Sentiment Analyser'), ('language_detector', 'Language Detector')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='model_version',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='trained_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aimodellog',
            name='training_data_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='themecluster',
            name='cluster_label',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='themecluster',
            name='top_keywords',
            field=models.JSONField(default=list, help_text='Top TF-IDF keywords for this cluster.'),
        ),
        migrations.AlterUniqueTogether(
            name='themecluster',
            unique_together={('week_start_date', 'cluster_index')},
        ),
        migrations.RemoveField(
            model_name='themecluster',
            name='avg_sentiment',
        ),
        migrations.CreateModel(
            name='FeedbackCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(db_index=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_assignments', to='nlp.themecluster')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_assignments', to='feedback.feedback')),
            ],
            options={
                'verbose_name': 'Feedback Cluster Assignment',
                'verbose_name_plural': 'Feedback Cluster Assignments',
                'db_table': 'rc_feedback_cluster',
                'unique_together': {('feedback', 'week_start_date')},
            },
        ),
    ]
