# Generated by Django 4.2.16 on 2026-05-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0004_alter_feedback_status_alter_sentiment_display_colour"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                ("broadcast_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("YSWD", "You Said We Did"),
                            ("General_Announcement", "General Announcement"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "body_en",
                    models.TextField(
                        help_text="Message body in English (source language)."
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all", "All opted-in users"),
                            ("by_location", "By location"),
                            ("by_category", "By category"),
                            ("by_feedback_ids", "By specific feedback IDs"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "target_days",
                    models.IntegerField(
                        default=30,
                        help_text="When target_type='by_category': look back this many days.",
                    ),
                ),
                (
                    "target_feedback_ids",
                    models.JSONField(
                        blank=True,
                        help_text="When target_type='by_feedback_ids': list of specific feedback_ids.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Scheduled", "Scheduled"),
                            ("Sending", "Sending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="NULL means send immediately on creation.",
                        null=True,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.IntegerField(default=0)),
                ("sent_count", models.IntegerField(default=0)),
                ("delivered_count", models.IntegerField(default=0)),
                ("failed_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Broadcast",
                "verbose_name_plural": "Broadcasts",
                "db_table": "rc_broadcast",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("template_key", models.CharField(db_index=True, max_length=60)),
                ("language", models.CharField(max_length=10)),
                (
                    "body",
                    models.TextField(
                        help_text="Template text with {variable} placeholders. Allowed: {reference_id}, {category}, {location}, {org_name}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System templates cannot be deleted, only edited.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Message Template",
                "verbose_name_plural": "Message Templates",
                "db_table": "rc_message_template",
                "ordering": ["template_key", "language"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="gateway_message_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="phone_number_encrypted",
            field=models.TextField(
                help_text="AES-256-GCM encrypted phone number. Use apps.common.encryption to read/write."
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["gateway_message_id"], name="idx_notif_gw_msg_id"
            ),
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcasts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="target_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="broadcasts",
                to="feedback.category",
            ),
        ),
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(
                fields=["template_key", "language"], name="idx_tmpl_key_lang"
            ),
        ),
        migrations.AddIndex(
            model_name="messagetemplate",
            index=models.Index(fields=["is_active"], name="idx_tmpl_active"),
        ),
        migrations.AlterUniqueTogether(
            name="messagetemplate",
            unique_together={("template_key", "language")},
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(fields=["status"], name="idx_broadcast_status"),
        ),
        migrations.AddIndex(
            model_name="broadcast",
            index=models.Index(fields=["scheduled_at"], name="idx_broadcast_scheduled"),
        ),
    ]
